# -*- coding: utf-8 -*-
"""arabic_sentiment_bert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6c9PT4AKjW7iPyLl7zdO9H8Hf7LMiDK
"""

from google.colab import drive
drive.mount('/content/drive')

import os

project_path = "/content/drive/MyDrive/arabic_sentiment_bert"

folders = [
    f"{project_path}/data/raw",
    f"{project_path}/data/processed",
    f"{project_path}/src",
    f"{project_path}/models",
    f"{project_path}/results",
    f"{project_path}/notebooks"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project structure created successfully")

!pip install transformers
!pip install torch
!pip install datasets
!pip install arabert
!pip install pandas
!pip install scikit-learn

from datasets import load_dataset

dataset = load_dataset("labr")

import pandas as pd

train_df = dataset["train"].to_pandas()

train_df = train_df[["text", "label"]]

train_df.to_csv("reviews.csv", index=False, encoding="utf-8")

print("Dataset saved")

import shutil

shutil.move(
    "reviews.csv",
    "/content/drive/MyDrive/arabic_sentiment_bert/data/raw/reviews.csv"
)

data_path ="/content/drive/MyDrive/arabic_sentiment_bert/data/raw/reviews.csv"

df = pd.read_csv(data_path)

df.head()

df["label"] = df["label"].apply(lambda x: 1 if x > 2 else 0)

import re

def normalize_arabic(text):

    text = re.sub("[إأٱآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "ء", text)
    text = re.sub("ئ", "ء", text)

    text = re.sub("[^ا-ي ]", "", text)

    return text

df["text"] = df["text"].apply(normalize_arabic)

from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(

    df["text"].tolist(),
    df["label"].tolist(),

    test_size=0.2,
    random_state=42
)

from transformers import AutoTokenizer

model_name = "aubmindlab/bert-base-arabertv02"

tokenizer = AutoTokenizer.from_pretrained(model_name)

train_encodings = tokenizer(

    train_texts,

    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(

    test_texts,

    truncation=True,
    padding=True,
    max_length=128
)

import torch

class ReviewDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):

        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])

        return item

    def __len__(self):

        return len(self.labels)

train_dataset = ReviewDataset(train_encodings, train_labels)

test_dataset = ReviewDataset(test_encodings, test_labels)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(

    model_name,

    num_labels=2
)

from transformers import Trainer
from transformers import TrainingArguments

training_args = TrainingArguments(

    output_dir="/content/drive/MyDrive/arabic_sentiment_bert/results",

    num_train_epochs=3,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=16,


    logging_dir=project_path + "/logs"
)

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=test_dataset
)

trainer.train()

import numpy as np
from sklearn.metrics import classification_report

predictions = trainer.predict(test_dataset)

preds = np.argmax(predictions.predictions, axis=1)

print(classification_report(test_labels, preds))

import os

os.listdir("/content/drive/MyDrive/arabic_sentiment_bert/models/arabic_sentiment_bert/models")

from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer

model_path = "/content/drive/MyDrive/arabic_sentiment_bert/models/arabic_sentiment_bert/models/sentiment_model"

model = AutoModelForSequenceClassification.from_pretrained(
    model_path,
    local_files_only=True
)

tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv02")

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model.to(device)

def predict(text):

    inputs = tokenizer(text, return_tensors="pt")

    inputs = {k: v.to(device) for k, v in inputs.items()}

    outputs = model(**inputs)

    pred = torch.argmax(outputs.logits).item()

    if pred == 1:
        return "Positive"
    else:
        return "Negative"

predict("المطعم رائع والطعام لذيذ")







from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

predictions = trainer.predict(test_dataset)

preds = np.argmax(predictions.predictions, axis=1)

cm = confusion_matrix(test_labels, preds)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Negative","Positive"],
    yticklabels=["Negative","Positive"]
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

log_history = trainer.state.log_history

train_loss = []
eval_loss = []
steps = []

for log in log_history:
    if "loss" in log:
        train_loss.append(log["loss"])
        steps.append(log["step"])
    if "eval_loss" in log:
        eval_loss.append(log["eval_loss"])

plt.figure(figsize=(8,5))

plt.plot(train_loss,label="Training Loss")
plt.plot(eval_loss,label="Validation Loss")

plt.xlabel("Steps")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")

plt.legend()

plt.show()

# ================================
# مقارنة BERT مع SVM
# ================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report


# =====================================
# 1️⃣ حساب نتائج BERT
# =====================================

bert_predictions = trainer.predict(test_dataset)

bert_preds = np.argmax(bert_predictions.predictions, axis=1)

bert_accuracy = accuracy_score(test_labels, bert_preds)

print("========== BERT RESULTS ==========")
print("BERT Accuracy:", bert_accuracy)
print(classification_report(test_labels, bert_preds))


# =====================================
# 2️⃣ تجهيز البيانات لنموذج SVM
# =====================================

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train = vectorizer.fit_transform(train_texts)
X_test = vectorizer.transform(test_texts)


# =====================================
# 3️⃣ تدريب نموذج SVM
# =====================================

svm_model = LinearSVC()

svm_model.fit(X_train, train_labels)


# =====================================
# 4️⃣ التنبؤ باستخدام SVM
# =====================================

svm_preds = svm_model.predict(X_test)

svm_accuracy = accuracy_score(test_labels, svm_preds)

print("\n========== SVM RESULTS ==========")
print("SVM Accuracy:", svm_accuracy)
print(classification_report(test_labels, svm_preds))


# =====================================
# 5️⃣ رسم مقارنة النماذج
# =====================================

models = ["BERT", "SVM"]
scores = [bert_accuracy, svm_accuracy]

plt.figure(figsize=(6,4))

plt.bar(models, scores, color=["blue","green"])

plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")

for i, v in enumerate(scores):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center')

plt.ylim(0,1)

plt.show()


# =====================================
# 6️⃣ طباعة المقارنة النهائية
# =====================================

print("\n========== FINAL COMPARISON ==========")

print(f"BERT Accuracy : {bert_accuracy:.3f}")
print(f"SVM Accuracy  : {svm_accuracy:.3f}")

if bert_accuracy > svm_accuracy:
    print("BERT performs better than SVM")
else:
    print("SVM performs better than BERT")

# Final Evaluation: Confusion Matrix + Graphs + Model Comparison


import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC


# مسار المشروع
project_path = "/content/drive/MyDrive/arabic_sentiment_bert/results"



# 1 حساب نتائج BERT

bert_predictions = trainer.predict(test_dataset)

bert_preds = np.argmax(bert_predictions.predictions, axis=1)

bert_accuracy = accuracy_score(test_labels, bert_preds)

print("========== BERT RESULTS ==========")
print("BERT Accuracy:", bert_accuracy)
print(classification_report(test_labels, bert_preds))


#
# 2 Confusion Matrix


cm = confusion_matrix(test_labels, bert_preds)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Negative","Positive"],
    yticklabels=["Negative","Positive"]
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - BERT")

plt.savefig(project_path + "/confusion_matrix.png")

plt.show()


#
# 3 Accuracy Graph
#

log_history = trainer.state.log_history

train_loss = []
eval_loss = []

for log in log_history:
    if "loss" in log:
        train_loss.append(log["loss"])
    if "eval_loss" in log:
        eval_loss.append(log["eval_loss"])

plt.figure(figsize=(8,5))

plt.plot(train_loss,label="Training Loss")
plt.plot(eval_loss,label="Validation Loss")

plt.xlabel("Training Steps")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")

plt.legend()

plt.savefig(project_path + "/training_graph.png")

plt.show()



# 4 تدريب نموذج SVM


vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train = vectorizer.fit_transform(train_texts)
X_test = vectorizer.transform(test_texts)

svm_model = LinearSVC()

svm_model.fit(X_train, train_labels)

svm_preds = svm_model.predict(X_test)

svm_accuracy = accuracy_score(test_labels, svm_preds)

print("\n========== SVM RESULTS ==========")
print("SVM Accuracy:", svm_accuracy)
print(classification_report(test_labels, svm_preds))


# 5 رسم مقارنة النماذج


models = ["BERT", "SVM"]
scores = [bert_accuracy, svm_accuracy]

plt.figure(figsize=(6,4))

plt.bar(models, scores, color=["blue","green"])

plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")

for i, v in enumerate(scores):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center')

plt.ylim(0,1)

plt.savefig(project_path + "/model_comparison.png")

plt.show()



# 6 طباعة النتيجة النهائية


print("\n========== FINAL COMPARISON ==========")

print(f"BERT Accuracy : {bert_accuracy:.3f}")
print(f"SVM Accuracy  : {svm_accuracy:.3f}")

if bert_accuracy > svm_accuracy:
    print("BERT performs better than SVM")
else:
    print("SVM performs better than BERT")


print("\nAll graphs saved in results folder")